# config/routes.yaml

controllers:
    resource: '../src/Controller/'
    type: attribute

dashboard:
    path: /dashboard
    controller: App\Controller\DashboardController::index

app_login:
    path: /login
    controller: App\Controller\LoginController::login
    methods: ['GET', 'POST']

app_profil:
    path: /profil
    controller: App\Controller\ProfilController::index
    # Remplacez le controller et path par les valeurs r√©elles de votre application


